name: Test

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]
                os: [macos-latest, ubuntu-latest, ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm test
              env:
                  CI: true
